//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.sales_invoice = new HashSet<sales_invoice>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Buyer { get; set; }
        public int ProductName { get; set; }
        public decimal ProductAmount { get; set; }
        public decimal ProductUnitPrice { get; set; }
    
        public virtual buyer buyer1 { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_invoice> sales_invoice { get; set; }
    }
}
