//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WholesaleBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Unit { get; set; }
        public int Category { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual unit unit1 { get; set; }
    }
}
